### ISSUE TITLE
Hamburg Hacknight Blogpost

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-project.github.io#39]
We agreed on Monday, February 15, 2016, 7pm.

**Comment by varac** [comment]
The eventbride annouce of the last hackday: https://www.eventbrite.de/e/hackday-pixelatedleap-easy-to-use-encrypted-email-with-decentralized-hosting-tickets-15216809888

**Comment by felixhammerl** [comment]
I don't know if we're gonna get the new website up in time, so here's the draft for blog post and eventbrite invitation as a gist instead...

https://gist.github.com/felixhammerl/34274d4206cf4413c7fc

**Comment by varac** [comment]
https://pixelated-project.org/2016/02/04/Hacknight-HH/
